weblights: weblights.farm
cameras:
  - full_url: rtsp://nw-cam.dc.farm/live/ch00_0
    tile_url: rtsp://nw-cam.dc.farm/live/ch01_0
  - full_url: rtsp://sw-cam.dc.farm/live/ch00_0
    tile_url: rtsp://sw-cam.dc.farm/live/ch01_0
  - full_url: rtsp://se-cam.dc.farm/live/ch00_0
    tile_url: rtsp://se-cam.dc.farm/live/ch01_0
  - full_url: rtsp://ne-cam.dc.farm/live/ch00_0
    tile_url: rtsp://ne-cam.dc.farm/live/ch01_0
